const $=id=>document.getElementById(id), message=t=>$('message').textContent=t;
async function api(url,o={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Erreur serveur');return d}
async function refreshSession(){try{const u=await api('/api/me');$('authCard').classList.add('hidden');$('dashboard').classList.remove('hidden');$('welcome').textContent=`Bienvenue ${u.name} 👋`;loadHistory()}catch{$('authCard').classList.remove('hidden');$('dashboard').classList.add('hidden')}}
$('registerBtn').onclick=async()=>{try{await api('/api/register',{method:'POST',body:JSON.stringify({name:$('registerName').value,email:$('registerEmail').value,password:$('registerPassword').value})});message('Compte créé. Vous pouvez vous connecter.')}catch(e){message(e.message)}};
$('loginBtn').onclick=async()=>{try{await api('/api/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});message('');refreshSession()}catch(e){message(e.message)}};
$('logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});refreshSession()};
$('analyzeBtn').onclick=async()=>{const s=$('symbol').value.trim().toUpperCase();if(!s)return message('Saisissez une crypto.');message('Analyse en cours...');try{const d=await api('/api/analyze/'+encodeURIComponent(s));$('analysisCard').classList.remove('hidden');$('analysisTitle').textContent=`${d.symbol} — ${d.signal}`;$('analysisGrid').innerHTML=`<div><span>Prix</span><b>${d.price.toLocaleString('fr-FR')} $</b></div><div><span>RSI</span><b>${d.rsi}</b></div><div><span>MACD</span><b>${d.macd}</b></div><div><span>Tendance</span><b>${d.trend}</b></div><div><span>Confiance</span><b>${d.confidence}%</b></div><div><span>Support / Résistance</span><b>${d.support} / ${d.resistance}</b></div>`;message('Analyse terminée.');loadHistory()}catch(e){message(e.message)}};
async function loadHistory(){try{const rows=await api('/api/history');$('history').innerHTML=rows.length?rows.map(r=>`<div class="history-row"><b>${r.symbol}</b><span>${r.signal}</span><span>${r.confidence}%</span><small>${r.created_at}</small></div>`).join(''):'Aucune analyse.'}catch(e){$('history').textContent=e.message}}
$('historyBtn').onclick=loadHistory;refreshSession();

$('tvBtn').onclick=async()=>{const f=$('tvFile').files[0];if(!f)return message('Sélectionnez une image.');const form=new FormData();form.append('file',f);try{const r=await fetch('/api/tradingview/analyze',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Erreur');$('tvResult').textContent=`${d.signal} — ${d.summary}`}catch(e){message(e.message)}};
$('alertBtn').onclick=async()=>{try{await api(`/api/alerts/${encodeURIComponent($('alertSymbol').value)}/${$('alertDirection').value}/${$('alertPrice').value}`,{method:'POST'});message('Alerte créée.');loadAlerts()}catch(e){message(e.message)}};
async function loadAlerts(){try{const rows=await api('/api/alerts');$('alerts').innerHTML=rows.length?rows.map(a=>`<div class="history-row"><b>${a.symbol}</b><span>${a.direction==='above'?'Au-dessus':'En dessous'}</span><span>${a.target_price}</span></div>`).join(''):'Aucune alerte.'}catch(e){}}
const oldRefresh=refreshSession;refreshSession=async function(){await oldRefresh();if(!$('dashboard').classList.contains('hidden'))loadAlerts();}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/static/sw.js').catch(()=>{});
